notifications:
  email: false
branches:
  except:
    - gh-pages
sudo: false
language: perl6
perl6:
  - latest
install:
  - rakudobrew build-zef
  - git clone git://github.com/cygx/p6-image-rgba.git image-rgba
  - zef install image-rgba
  - make pngcheck
script:
  - make
  - zef install .
