notifications:
  email: false
branches:
  except:
    - gh-pages
sudo: false
language: perl6
perl6:
  - latest
install:
  - rakudobrew build-zef
  - zef install Image::RGBA
  - make pngcheck
script:
  - make
  - zef install .
